export const navItems = [
  { path: '/dashboard', label: 'Dashboard' },
  { path: '/users', label: 'Users' },
  { path: '/batches', label: 'Batches' },
  { path: '/courses', label: 'Courses' },
  { path: '/carousel', label: 'Carousel' },
  { path: '/icons', label: 'Icons' },
  { path: '/ebooks', label: 'Ebooks' },
  { path: '/notes', label: 'Notes' },
  { path: '/tests', label: 'Tests' },
  { path: '/faqs', label: 'FAQ' },
  { path: '/online-classes', label: 'Online Class' },
  { path: '/current-affairs', label: 'Current Affairs' },
  { path: '/jobs', label: 'Jobs' },
  { path: '/testimonials', label: 'Testimonials' },
  { path: '/cms', label: 'CMS' },
]
